specify_pose: Add proposal
ignitionrobotics/sdf_tutorials pull request #37
Opened 2020-07-29 16:47 UTC by EricCousineau-TRI

Towards #252

Low-priority for review w.r.t. composition at the moment, but I would still love to land this for SDFormat 1.8 in general.

2020-07-30 18:40 UTC, EricCousineau-TRI commented
@sammy-tri Would you be able to review this too?

2020-09-03 18:54 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37)* status: all files reviewed, 13 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, and @sammy-tri)

___
*[specify_pose/proposal.md, line 285 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MD_gci49X1PjOgcr9OW:-MGKJJOdEjCGtPsHg1_K:b-49rjhc) ([raw file](https://github.com/osrf/sdf_tutorials/blob/921244bca7068050d5d2c74b9dec58bf0f46ddb3/specify_pose/proposal.md#L285)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I think that's only a facet of URDF / SDFormat doing those. I'd prefer to have a representation with fewer weird singularities / wraparound, which a quaternion provides.

I could see it as useful for simple text-based upgrades of files, but I dunno how I feel about that if we can just automate the up-conversion process...

May relax it when I revisit this next week.
</blockquote></details>

Per f2f, will keep it given legacy.


<!-- Sent from Reviewable.io -->

2020-09-17 17:41 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @azeey, @sammy-tri, and @scpeters)

___
*[specify_pose/proposal.md, line 146 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MDVma0OCcmkIsmFOzHk:-MHS8lua0tsdKbqDVaz_:b-82lh6i) ([raw file](https://github.com/osrf/sdf_tutorials/blob/921244bca7068050d5d2c74b9dec58bf0f46ddb3/specify_pose/proposal.md#L146)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This should be concretely verified reflect the following value:
```
#include <limits>
std::numeric_limits<double>::max_digits10
// 17
```
Used a brief cling Binder session:
https://mybinder.org/v2/gh/jupyter-xeus/xeus-cling/e1ebf168aff5d2566dff29b61b14db3a40ca0fac?filepath=notebooks%2Fxcpp.ipynb

FWIW In Python:
```
import numpy as np

print(np.finfo(np.float64).precision)
# 15
```

Should find docs reconciling the two
</blockquote></details>

Done. Didn't reconcile, but just stuck with C++'s limits.

(Assumes a common architecture, but :shrug: )
___
*[specify_pose/proposal.md, line 282 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MDp2cQm8hCmQTOa7MWc:-MHS8uz56LwBHHGVLMW1:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/921244bca7068050d5d2c74b9dec58bf0f46ddb3/specify_pose/proposal.md#L282)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I don't think we should deprecate the default rotation type used in old versions of SDFormat and URDF.
</blockquote></details>

Done.
___
*[specify_pose/proposal.md, line 285 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MD_gci49X1PjOgcr9OW:-MHS8w9_1sGGV2X4xYnV:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/921244bca7068050d5d2c74b9dec58bf0f46ddb3/specify_pose/proposal.md#L285)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per f2f, will keep it given legacy.
</blockquote></details>

Done.
___
*[specify_pose/proposal.md, line 359 at r2](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MG5J2YS6tz11iSEC8QH:-MHS8wjm2AGmL8dgW3Eg:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/a3ea0eee429a06afe48fb37828d0ddc73392a5e8/specify_pose/proposal.md#L359)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I think you need a blank line above this as it's not rendering properly:

http://sdformat.org/tutorials?tut=better_pose_proposal&cat=pose_semantics_docs&branch=issue-sdformat-252-pose-degrees&repo=https%3A%2F%2Fgithub.com%2FEricCousineau-TRI%2Fsdf_tutorials-1#collada
</blockquote></details>

Done.
___
*[specify_pose/proposal.md, line 379 at r2](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MG5JAAVE0GtXjJMJeMz:-MHS8x9L6-14qKxRHt6g:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/a3ea0eee429a06afe48fb37828d0ddc73392a5e8/specify_pose/proposal.md#L379)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

another blank line needed above this:

http://sdformat.org/tutorials?tut=better_pose_proposal&cat=pose_semantics_docs&branch=issue-sdformat-252-pose-degrees&repo=https%3A%2F%2Fgithub.com%2FEricCousineau-TRI%2Fsdf_tutorials-1#gltf
</blockquote></details>

Done.
___
*[specify_pose/proposal.md, line 395 at r2](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MG5JFwV9u73ovYYc3Kp:-MHS8xW96LMUr4QSgAAh:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/a3ea0eee429a06afe48fb37828d0ddc73392a5e8/specify_pose/proposal.md#L395)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

blank line needed above this

http://sdformat.org/tutorials?tut=better_pose_proposal&cat=pose_semantics_docs&branch=issue-sdformat-252-pose-degrees&repo=https%3A%2F%2Fgithub.com%2FEricCousineau-TRI%2Fsdf_tutorials-1#vrml
</blockquote></details>

Done.
___
*[specify_pose/proposal.md, line 413 at r2](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MG5LteM3RAaE9AqgzAc:-MHS8xgz1vepy-FHePkr:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/a3ea0eee429a06afe48fb37828d0ddc73392a5e8/specify_pose/proposal.md#L413)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

does this note apply to the SKEL format only?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-17 17:44 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37)* status: 1 of 2 files reviewed, 12 unresolved discussions (waiting on @azeey, @sammy-tri, and @scpeters)

*[a discussion](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MHS9J0a3JRlPXBX4uHr:-MHS9J0a3JRlPXBX4uHs:b-ag9nz9) (no related file):*
Thinking on this more, perhaps I could be convinced of something like a 4-tuple axis-angle, where axis will be normalized (magnitude *always* ignored), and degrees will specify the angle.

Then that can make certain rotations (e.g. rotate about `normalized([1, 1, 1])` by 45 degrees) a bit easier to express by hand, rather than resorting to a lookup for rpy combos or quaternions.

---


<!-- Sent from Reviewable.io -->

2020-09-17 18:05 UTC, sammy-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37)* status: 1 of 2 files reviewed, 12 unresolved discussions (waiting on @azeey and @scpeters)

___
*[specify_pose/proposal.md, line 257 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MD_gQ2S2YiwMSRriYmr:-MHSEOHM3zwLmnA-RcGx:bthysyn) ([raw file](https://github.com/osrf/sdf_tutorials/blob/921244bca7068050d5d2c74b9dec58bf0f46ddb3/specify_pose/proposal.md#L257)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

this doesn't appear to be resolved?


<!-- Sent from Reviewable.io -->

2020-09-18 21:45 UTC, scpeters reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37)* status: all files reviewed, 7 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2020-10-19 12:23 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37)* status: all files reviewed, 8 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MK-o-8d9POK0eYbpKLW:-MK-o-8e-Mf9I9yGTwNY:b-4vqe55) (no related file):*
Should mention:
https://www.ros.org/reps/rep-0103.html

---


<!-- Sent from Reviewable.io -->

2021-02-25 20:25 UTC, EricCousineau-TRI commented
Punting on this for SDFormat 1.8

2021-06-14 13:25 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @azeey, @sammy-tri, and @scpeters)

___
*[specify_pose/proposal.md, line 257 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MD_gQ2S2YiwMSRriYmr:-Mc9gizj7U65uBRcCP2Z:b-qsx7uj) ([raw file](https://github.com/osrf/sdf_tutorials/blob/921244bca7068050d5d2c74b9dec58bf0f46ddb3/specify_pose/proposal.md#L257)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

this doesn't appear to be resolved?
</blockquote></details>

Done. Oops!


<!-- Sent from Reviewable.io -->

2021-06-14 13:27 UTC, EricCousineau-TRI reviewed
FYI @azeey @aaronchongth Given prior convos, I've hoisted the "via attribute" alternative.

My desire: Let's review this proposal in its draft form, and merge it. Afterwards, we can PR any add'l evolution.

> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-:-Mc9glqD61i5cJ4j74r1:bgkmz92)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @azeey, @sammy-tri, and @scpeters)



<!-- Sent from Reviewable.io -->

2021-06-14 13:29 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @azeey, @sammy-tri, and @scpeters)

*[a discussion](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MDW4ujNCDshfiOvTCq3:-Mc9hGiwEYCHpwpIe7bT:b-nsf20z) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per VC, should ensure this proposal covers what happens when poses are serialized to an XML document.

Options:
- Always output quaternion (least loss of precision?)
- Always output quatnerion, unless RPY can represent it to some degree of precision?
- ?
</blockquote></details>

As we've talked about this, I believe we should start in the following fashion:

- For output, provide the *option* to specify pose output. By default, it will radians (for simplicity).
- For degrees and other representations, we can add an option for a "snap-to-grid" value, e.g. if your value is close to 45 degrees along whatever axes by some threshold (user specified), it'll get replaced.

---


<!-- Sent from Reviewable.io -->

2021-06-14 17:23 UTC, azeey commented
___
*[specify_pose/proposal.md, line 320 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McAXWzV0tH8hVggUYf9:-McAXWzV0tH8hVggUYfA:bmrwqzc) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L320)):*
> ```Markdown
> #### 1.2 Deprecate old `//pose` representation
> 
> The existing usage of `//pose` will remain for SDFormat 1.8, but will be
> ```

I was under the impression that we were **not** deprecating the existing usage of `//pose` per https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MDp2cQm8hCmQTOa7MWc.


<!-- Sent from Reviewable.io -->

2021-06-15 16:20 UTC, aaronchongth requested changes
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37)* status: 0 of 2 files reviewed, 16 unresolved discussions (waiting on @azeey, @EricCousineau-TRI, @sammy-tri, and @scpeters)

___
*[specify_pose/proposal.md, line 6 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McFRUtXEtPkMjqGrXSf:-McFRUtXEtPkMjqGrXSg:buujeon) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L6)):*
> ```Markdown
> Eric Cousineau `<eric.cousineau@tri.global>`,
> * **Status**: Draft
> * **SDFormat Version**: 1.8
> ```

Would we be targeting 1.9 now?
___
*[specify_pose/proposal.md, line 118 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McFOXTKEqpNtdLD5EFs:-McFOXTL-Ze4b0Py8jJ8:b1risp1) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L118)):*
> ```Markdown
> and rotation as separate elements.
> 
> For Option B, `libsdformat` and SDFormat tutorials should encourage additionaly
> ```

nit: typo "additional whitespaces"
___
*[specify_pose/proposal.md, line 149 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McFPAZOC_-47bdtZ9iB:-McFPAZOC_-47bdtZ9iC:b-u6uxss) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L149)):*
> ```Markdown
> *Use `//pose/@rotation_type`*
> 
> This will help descrease the verbosity; however, it will still make the visual
> ```

nit: typo "decrease"
___
*[specify_pose/proposal.md, line 195 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McFPuQR4S9IhW1QW2xb:-McFPuQR4S9IhW1QW2xc:bs2dz7z) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L195)):*
> ```Markdown
>     * This should be used when the rotation should generally be human-readable.
> * `rpy_radians` - Same as `rpy_degrees`, but with radians as the units for each
> angel. This is provided for legacy purposes and ease of conversion.
> ```

nit: typo "angle"
___
*[specify_pose/proposal.md, line 259 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McFQPK58oL5x5WrfjhG:-McFQPK58oL5x5WrfjhH:b-yo1dyu) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L259)):*
> ```Markdown
> -->
> 
> **Alternatives Considred**
> ```

nit: typo "Considered"
___
*[specify_pose/proposal.md, line 325 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McFRuKl5HHzjcFI_CRI:-McFRuKl5HHzjcFI_CRJ:b-wdzywi) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L325)):*
> ```Markdown
> This is only valid for Option B.
> 
> #### 1.2.1 Conversion to SDFormat 1.8
> ```

Would this be 1.9? This would apply to the next line too
___
*[specify_pose/proposal.md, line 342 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McFSFtU2k_WFgos4ZOu:-McFSFtU2k_WFgos4ZOv:b-xrqtcm) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L342)):*
> ```Markdown
> - There should be an admission for "snapping to" well known values in either
>   representation, within a given angular tolerance (degrees). This can help
>   converting exisitng models to more readable units, and possibly with better
> ```

nit: typo "convert existing"


<!-- Sent from Reviewable.io -->

2021-06-17 18:01 UTC, EricCousineau-TRI reviewed
Thanks for the comments! I think I've addressed all outstanding discussion poinst

> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-:-McQ7XXX7qOEdcZQA0NC:bw2df1k)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @aaronchongth, @azeey, @EricCousineau-TRI, @sammy-tri, and @scpeters)

*[a discussion](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MDW4ujNCDshfiOvTCq3:-McQ6WC338G7wHoIfSf0:b5i2gu5) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

As we've talked about this, I believe we should start in the following fashion:

- For output, provide the *option* to specify pose output. By default, it will radians (for simplicity).
- For degrees and other representations, we can add an option for a "snap-to-grid" value, e.g. if your value is close to 45 degrees along whatever axes by some threshold (user specified), it'll get replaced.
</blockquote></details>

Done. (encoded in proposal)

---
*[a discussion](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MHS9J0a3JRlPXBX4uHr:-McQ6Yh66DxizuxAuLNg:b-1smck9) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Thinking on this more, perhaps I could be convinced of something like a 4-tuple axis-angle, where axis will be normalized (magnitude *always* ignored), and degrees will specify the angle.

Then that can make certain rotations (e.g. rotate about `normalized([1, 1, 1])` by 45 degrees) a bit easier to express by hand, rather than resorting to a lookup for rpy combos or quaternions.
</blockquote></details>

Done. Ignoring for now.

---
*[a discussion](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MK-o-8d9POK0eYbpKLW:-McQ6_fvDxfNucx9z0ut:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Should mention:
https://www.ros.org/reps/rep-0103.html
</blockquote></details>

Done.

---
___
*[specify_pose/proposal.md, line 320 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McAXWzV0tH8hVggUYf9:-McQ6wSc9q2KMpEjQVnI:b-45yjmd) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L320)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I was under the impression that we were **not** deprecating the existing usage of `//pose` per https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MDp2cQm8hCmQTOa7MWc.
</blockquote></details>

Done. oops!

FWIW Also, I think your link was broken; Reviewable hyperlinks can be finicky.
I believe this is the link in GitHub you meant? (though imprecise, as it doesn't pinpoint exact convo)
https://github.com/osrf/sdf_tutorials/pull/37#pullrequestreview-460154470
___
*[specify_pose/proposal.md, line 325 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McFRuKl5HHzjcFI_CRI:-McQ7J1bEsZ-TqNt6ZuK:b-896fix) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L325)):*
<details><summary><i>Previously, aaronchongth (Aaron Chong) wrote…</i></summary><blockquote>

Would this be 1.9? This would apply to the next line too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-25 16:11 UTC, azeey approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> The proposal still leans heavily toward `//pose/translation` and `//pose/rotation`. If we end up not pursuing those, it would be good to update some of the sections and examples showing `//pose/@rotation_type`.

> Reviewed 1 of 2 files at r4, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-:-Md2vq9S14_M8bb1RQKv:bjfubny)* status: all files reviewed, 7 unresolved discussions (waiting on @aaronchongth, @EricCousineau-TRI, and @sammy-tri)

___
*[specify_pose/proposal.md, line 146 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-MDVma0OCcmkIsmFOzHk:-Md2pLeN8o3iZSupZqND:b-bqxv7e) ([raw file](https://github.com/osrf/sdf_tutorials/blob/921244bca7068050d5d2c74b9dec58bf0f46ddb3/specify_pose/proposal.md#L146)):*
> ```
> std::numeric_limits<double>::max_digits10
> ```
`std::numeric_limits<double>::digits10` is 15, which I think is what `np.finfo` is providing. I'm still trying to understand the difference between `max_digits10` and `digits10` and its implication on parsed input values.  From https://stackoverflow.com/a/56515598/283225

> `digits10`: Given a value in decimal representation, how many decimal digits can be guaranteedly preserved if converted from decimal to a selected binary format and back (with default rounding).
> `max_digits10`: Given a value in binary format, how many decimal digits are needed if value is converted to decimal format and back to original binary format (again, with default rounding) to get the original value unchanged.

So I think using `max_digits10` when outputting values makes sense because that's the string representation that captures the full precision of the number being generated.
___
*[specify_pose/proposal.md, line 320 at r5](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-McAXWzV0tH8hVggUYf9:-Md-CRNf8J3N54zWcPbA:b9oe615) ([raw file](https://github.com/osrf/sdf_tutorials/blob/c7702fe91ab524257131ddc51be946a537c45bc1/specify_pose/proposal.md#L320)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. oops!

FWIW Also, I think your link was broken; Reviewable hyperlinks can be finicky.
I believe this is the link in GitHub you meant? (though imprecise, as it doesn't pinpoint exact convo)
https://github.com/osrf/sdf_tutorials/pull/37#pullrequestreview-460154470
</blockquote></details>

I'll stop using reviewable hyperlinks. It seems to work for me, but not for others. It must be tied to my session.
___
*[specify_pose/proposal.md, line 28 at r7](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-Md-D60p9WgbEJxGiMAI:-Md-D60p9WgbEJxGiMAJ:bnue8sp) ([raw file](https://github.com/osrf/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L28)):*
> ```Markdown
> 
> This proposal intends to resolve on point (1) by adding `//pose/rotation/@type`
> where degrees can be specified, and *could* address point by structuring the
> ```

nit: address point **(2)**
___
*[specify_pose/proposal.md, line 35 at r7](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-Md-DIYl9Sr-BL6Yzi03:-Md-DIYl9Sr-BL6Yzi04:btzlh26) ([raw file](https://github.com/osrf/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L35)):*
> ```Markdown
> Make a bullet list of all major sections:
> 
> TBD
> ```

nit: Can this TBD be filled out now?
___
*[specify_pose/proposal.md, line 50 at r7](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-Md2V15sEgKs5lDvJKQT:-Md2V15sEgKs5lDvJKQU:b-1b3tbz) ([raw file](https://github.com/osrf/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L50)):*
> ```Markdown
> 
> ```xml
> <pose>{xyz} {rpy_radians}</pose>  <!-- Old format; deprecated. -->
> ```

nit: Can you remove "deprecated"?
___
*[specify_pose/proposal.md, line 170 at r7](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-Md2WI-ADPfYsWqcSLvS:-Md2WI-ADPfYsWqcSLvT:b4dhnri) ([raw file](https://github.com/osrf/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L170)):*
> ```Markdown
> While SDFormat could use attributes for these values like URDF does, it would
> go against the convention used for other elements (e.g.
> `//joint/axis/translation`, `//inertia/ixx,...`).
> ```

nit: `//joint/axis/translation` -> `//joint/axis/xyz`?


<!-- Sent from Reviewable.io -->

2021-06-28 04:02 UTC, aaronchongth approved these changes
LGTM!

> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/37#-:-MdFliEEAy08dvZdqVGe:b-85i648)* status: all files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @sammy-tri)



<!-- Sent from Reviewable.io -->

2021-07-26 04:24 UTC, EricCousineau-TRI commented
Addressed all points! Unable to publish changes on Reviewable, though (I guess due to migration to `github.com/ignitionrobotics`?)

2021-07-26 14:04 UTC, azeey commented
Testing comments





<!-- Sent from Reviewable.io -->

2021-07-26 14:05 UTC, EricCousineau-TRI commented
Testing comments again





<!-- Sent from Reviewable.io -->

2021-07-26 14:06 UTC, azeey commented
___
*[specify_pose/proposal.md, line 35 at r7](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-Md-DIYl9Sr-BL6Yzi03:-MfY7iEDCFgM4fzwLYsX:b-fa493g) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L35)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

nit: Can this TBD be filled out now?
</blockquote></details>

Test reviewable comment.


<!-- Sent from Reviewable.io -->

2021-07-26 14:06 UTC, EricCousineau-TRI commented
___
*[specify_pose/proposal.md, line 28 at r7](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-Md-D60p9WgbEJxGiMAI:-MfW2EEh7sI2kSfHU2O6:b-896fix) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L28)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

nit: address point **(2)**
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 03:28 UTC, azeey commented
___
*[specify_pose/proposal.md, line 51 at r9](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-MfkH1jtDo7yBbNakRhT:-MfkH1jtDo7yBbNakRhU:bz51m3x) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/e4df1976b0a9b2980b48a3c591857e6cc849c4e8/specify_pose/proposal.md#L51)):*
> ```Markdown
> should be *either* one of the following formats:
> 
> ### Option A: Child Elements
> ```

Now that we've pretty much converged on `//pose/@rotation_type`, I feel like this section can be moved to the "Alternatives Considered" section. Thoughts?


<!-- Sent from Reviewable.io -->

2021-07-29 03:28 UTC, azeey commented
___
*[specify_pose/proposal.md, line 50 at r7](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-Md2V15sEgKs5lDvJKQT:-MfkFexY8U5L8lr6DS5F:b-896fix) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L50)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

nit: Can you remove "deprecated"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 17:51 UTC, azeey reviewed
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[specify_pose/proposal.md, line 170 at r7](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-Md2WI-ADPfYsWqcSLvS:-MfkFrcDDsHd6KzfPHe6:b-896fix) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L170)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

nit: `//joint/axis/translation` -> `//joint/axis/xyz`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 18:28 UTC, EricCousineau-TRI reviewed
> Dismissed @sammy-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[specify_pose/proposal.md, line 146 at r1](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-MDVma0OCcmkIsmFOzHk:-MdHtQjVBZOi8luZbFw3:bxi7sne) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/921244bca7068050d5d2c74b9dec58bf0f46ddb3/specify_pose/proposal.md#L146)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

> ```
> std::numeric_limits<double>::max_digits10
> ```
`std::numeric_limits<double>::digits10` is 15, which I think is what `np.finfo` is providing. I'm still trying to understand the difference between `max_digits10` and `digits10` and its implication on parsed input values.  From https://stackoverflow.com/a/56515598/283225

> `digits10`: Given a value in decimal representation, how many decimal digits can be guaranteedly preserved if converted from decimal to a selected binary format and back (with default rounding).
> `max_digits10`: Given a value in binary format, how many decimal digits are needed if value is converted to decimal format and back to original binary format (again, with default rounding) to get the original value unchanged.

So I think using `max_digits10` when outputting values makes sense because that's the string representation that captures the full precision of the number being generated.
</blockquote></details>

OK Sweet, thanks for checking! TBH, I'm still a bit confused on why NumPy doesn't present similar information, but perhaps I need to ponder a bit more!
___
*[specify_pose/proposal.md, line 257 at r1](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-MD_gQ2S2YiwMSRriYmr:-MdHtYk9B37SdvNjkX36:b-896fix) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/921244bca7068050d5d2c74b9dec58bf0f46ddb3/specify_pose/proposal.md#L257)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Oops!
</blockquote></details>

Done.
___
*[specify_pose/proposal.md, line 35 at r7](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-Md-DIYl9Sr-BL6Yzi03:-MfW2EvVCu9s4hmS98Je:b-896fix) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L35)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

nit: Can this TBD be filled out now?
</blockquote></details>

Done.
___
*[specify_pose/proposal.md, line 50 at r7](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-Md2V15sEgKs5lDvJKQT:-MfW2FcBAvQwlNNiCxk-:b-896fix) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L50)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

nit: Can you remove "deprecated"?
</blockquote></details>

Done.
___
*[specify_pose/proposal.md, line 170 at r7](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-Md2WI-ADPfYsWqcSLvS:-MfW2GZ0Aba6RjJtYjXL:b-896fix) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/8f9c46d97761640d42b4fb9ebd19f9f8aec6752b/specify_pose/proposal.md#L170)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

nit: `//joint/axis/translation` -> `//joint/axis/xyz`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 18:29 UTC, EricCousineau-TRI reviewed
> Dismissed @azeey from a discussion.
> *[Reviewable](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[specify_pose/proposal.md, line 51 at r9](https://reviewable.io/reviews/ignitionrobotics/sdf_tutorials/37#-MfkH1jtDo7yBbNakRhT:-MfnWc429RAggCvIeRTb:bkcquu8) ([raw file](https://github.com/ignitionrobotics/sdf_tutorials/blob/e4df1976b0a9b2980b48a3c591857e6cc849c4e8/specify_pose/proposal.md#L51)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Now that we've pretty much converged on `//pose/@rotation_type`, I feel like this section can be moved to the "Alternatives Considered" section. Thoughts?
</blockquote></details>

OK Per VC, will do this as follow-up PR!


<!-- Sent from Reviewable.io -->

2021-07-29 18:30 UTC, EricCousineau-TRI commented
Assuming all discussions were resolved via Reviewable, so these should be good to go - merging!

2021-07-29 18:30 UTC, merged