Add instructions for sdf12 to build usd support
ignitionrobotics/sdf_tutorials pull request #65
Opened 2022-03-08 04:20 UTC by koonpeng

# 🎉 New feature

## Summary

Add instructions for sdf12 to build usd support.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-03-08 08:36 UTC, ahcorde requested changes

2022-03-08 08:36 UTC, ahcorde commented on install/tutorial_12.md
> +##### USD
Add a note that USD support is only available from sources

2022-03-08 08:38 UTC, ahcorde requested changes
Yo need to add this file in the `manifest.xml`

2022-03-10 09:36 UTC, koonpeng commented
> Yo need to add this file in the `manifest.xml`

updated manifest

2022-03-10 11:33 UTC, ahcorde requested changes

2022-03-10 11:33 UTC, ahcorde commented on install/tutorial_12.md
> +##### USD
@koonpeng this comment is still pending

2022-03-14 07:45 UTC, koonpeng commented
@ahcorde sorry about that, added the note now.

2022-03-14 13:43 UTC, ahcorde approved these changes

2022-03-15 14:56 UTC, azeey commented on install/tutorial_12.md
> +
For those who don't know what USD is, it would be great to have a sentence describing what it is with a link to the official website.

2022-03-15 14:57 UTC, azeey commented
btw, here's the preview: http://sdformat.org/tutorials?tut=install&ver=%3E%3D+12&cat=developers&branch=usd-install

2022-03-16 05:22 UTC, koonpeng commented
@azeey added `cd` and description of USD

2022-03-16 13:25 UTC, azeey approved these changes

2022-03-16 13:31 UTC, merged